### PR TITLE
Spi work (Note: 1 invasive fix)

### PR DESCRIPTION
**Pull request by the-snowwhite**
This adds 2 configs for the DExx_Cramps 1 with bspi and 1 with dbspi (buffered spi with decoded chip selects).
However to get the spi's to not send 3 datastreams for each write I had to change the write timing in the global hm2 uio qsys core(set_interface_property slave writeWaitTime 0):
https://github.com/the-snowwhite/mksocfpga/commit/b988a7b7218fd1b8b5664d84436ddc6efca4c025#diff-866caa37e2c4e9882a0a92a9672af4ceR147
@cdsteinkuehler 
Seems like every time a hm2 core register was written there has been 2 extra writes/clock cycles that so far has gone unnoticed ... ?

### CODE REVIEW

**Comment by ArcEye** [comment]
@cdsteinkuehler is obviously away - but I have no idea about the extra clock cycles.

Leaving for now.

**Comment by the-snowwhite** [comment]
Ok 
Not that there are lots of PR's in line..
Problem is that I have no easy way of testing the DExx_xx_DB25 bitfiles as I have no setup's running on the DB25 adaptor...

**Comment by cdsteinkuehler** [comment]
It sounds like the multiple write issue is related to the handshake on the Avalon bus.  I always use the wait signal, but the bus can be setup to have a fixed number of wait states and no handshake, which is what I think was causing the apparent 3x writes (one actual write, plus two clocks with the write signals in the same state due to the bus setup).

The other changes seem fine, merging.

**Comment by the-snowwhite** [comment]
Went thru the build system smoth like butter :-)

**Pull request merged**
