### PR TITLE
Sserial work

### PR DESCRIPTION
**Pull request by the-snowwhite**
DExx: Adds SSerial support and bitfile for the new [ST-DC1 daughtercard](https://github.com/ShadeTechnik/socfpga-developement-OSHW/tree/master/DE10-Nano/ST-DC1%20daughtercard)
Plus an update to the readme
And some config enhancements 
(mux enable/disable)
(select pin numbers for capsense in SV config file)

### CODE REVIEW

**Comment by the-snowwhite** [comment]
??? ... Oh I see
@blazini36 
You can rebase and resubmit your update to the pin file after this PR has been merged by @cdsteinkuehler or someone else...

**Comment by ArcEye** [comment]
@the-snowwhite 
Is this ready to go `as-is`?

The other PR can be merged later and amended if necessary.

**Comment by the-snowwhite** [comment]
Yes I's ready and tested

**Comment by ArcEye** [comment]
Ok, merged, I'll wait to ensure the packages come through and then look at #110

**Pull request merged**
