### PR TITLE
Add Hm2 soc cramps hal config example + firmware path length expansion + cleanup

### PR DESCRIPTION
**Pull request by the-snowwhite**
Some cleanups and doc improvements related to issue #23 
Cleanup of some "glue logic" in top file: 
moved led counter into new module led_blinker.
added gpio_mux module that can work as both straight and for the @cdsteinkuehler DB-25 adaptor board.

### CODE REVIEW

**Comment by mhaberler** [comment]
I described the [upgrade for the image to use the 4.1 kernel in detail here](https://gist.github.com/mhaberler/89a813dc70688e35d8848e8e467a1337#upgrading-to-the-41-rt-preempt-kernel-supporting-device-tree-overlays)

This **works** provided you follow the steps - I verified these steps. Not sure why I doing this when it is reinvented afterwards with contradicting information in this readme.

But I do not exclude an error. If you find an error in the gist, **comment on the gist and help fix it**

I also suggested diverting discussion of image issues to https://github.com/machinekit/machinekit/issues/915 . Can we do that? 

we need to work towards a **single set of maintained documentation**, not a random collection of semi-outdated and contradicting developer notes, scribblings and whatnot, the confusion is already bad enough

**Comment by the-snowwhite** [comment]
> we need to work towards a single set of maintained documentation

Yes very much indeed.

As your gist includes updating the uio dkms package, I have to differ form those instructions by totally removing the hm2reg_uio driver before upgrading the kernel. To get the generic kernel driver active.

Also what seemed to go wrong was the u-boot env variables, and your gist seems to assume an unmodified u-boot from 3.10 to 4.1 ?

**Comment by mhaberler** [comment]
I think I will have a 4.1 image with machinekit source install tomorrow
yes, uboot is unmodified

**Comment by the-snowwhite** [comment]
Hmmm I'll try again once I get my current de0 nano ghrd commit finished.

I may just have to reset the u-boot variables if booting and network support goes haywire again..

**Comment by mhaberler** [comment]
ist his now superseded by #34 ?

**Comment by the-snowwhite** [comment]
Yes #34 is the delayed finish up, suposed to replac / --amend the last commit here.

**Pull request closed without merging**
