### PR TITLE
Work2 clean

### PR DESCRIPTION
**Pull request by the-snowwhite**
Some cleanups and doc improvements  related to issue #23 
Cleanup of some "glue logic" in top file: 
moved led counter into new module led_blinker.
added gpio_mux module that can work as both straight and for the @cdsteinkuehler DB-25 adaptor board.

### CODE REVIEW

**Comment by mhaberler** [comment]
@the-snowwhite - can I suggest to again reset mixed on master and re-commit (that is _8_ commits just changing the IRQ readme!)

**Comment by mhaberler** [comment]
btw the current master seems broken too, see https://jenkins.machinekit.io/job/mksocfpga/40/console
not sure if it is master or me, as I was working on the jenkins config at the time

do these commands work ?

`````
#!/bin/bash -e
export PATH="$PATH:/root/altera_lite/15.1/quartus/bin/:/root/altera_lite/15.1/quartus/sopc_builder/bin/"

cd HW/QuartusProjects/DE0_NANO_SOC_GHRD/

make -j$(nproc) rbf
``````

which yields
`````

00:00:06.988 make: *** No rule to make target 'output_files/DE0_NANO.sof', needed by 'output_files/DE0_NANO.rbf'.  Stop.

````

**Comment by the-snowwhite** [comment]
Darn .... I seem to be unable to sync my master git commit history to upstream.

So every time I try to make a clean start over all the old commits pop back up ...

**Comment by the-snowwhite** [comment]
I am now going to kill that mksocfpga fork and start over from a clean slate.

Menawhile can you look into: https://github.com/machinekit/machinekit/pull/942
when its past chekking ?

**Comment by the-snowwhite** [comment]
ok retry

**Pull request closed without merging**
