### PR TITLE
Major Zynq update

### PR DESCRIPTION
**Pull request by dkhughes**
This PR includes a lot of changes on the Xilinx side such as:

- ZTurn reference project with a custom carrier
- Custom IP to support reference projects
- Split IOBits bus to allow for logic insertion in hardware design
- FWID support on the Xilinx side based on the Altera .mif file format.

It is missing the ZTurn IO carrier project, but that is following shortly.

### CODE REVIEW

**Comment by mhaberler** [comment]
want to pull --rebase to stay fast-forward, and push --force?

**Comment by dkhughes** [comment]
Yes, I can work on that more. I'm getting lots of conflicts as I rebase the remaining commits. I rebased about 30 of them, hehe.

**Comment by mhaberler** [comment]
uhm I see ;)

**Comment by mhaberler** [comment]
make it optional then ;)

**Pull request merged**
